package one.wabbit.random

import kotlin.test.Test
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith

class ThreefryRandomSpec {
    @Test
    fun hash_matches_exported_jax_vectors() {
        for ((key, count, expected) in hashVectors) {
            assertContentEquals(
                expected,
                ThreefryRandom.hash(
                    key0 = key[0],
                    key1 = key[1],
                    count0 = count[0],
                    count1 = count[1],
                ),
            )
        }
    }

    @Test
    fun split_matches_exported_jax_vectors() {
        val mutable = ThreefryRandom(0L)
        val immutable = ThreefryRandom.Immutable(0L)

        assertEquals(splitVector.map { it.toList() }, mutable.split(4).map { listOf(it.key0, it.key1) })
        assertEquals(splitVector.map { it.toList() }, immutable.split(4).map { listOf(it.key0, it.key1) })
    }

    @Test
    fun fold_in_matches_exported_jax_vector() {
        val mutable = ThreefryRandom(0L).foldIn(7)
        val immutable = ThreefryRandom.Immutable(0L).foldIn(7)

        assertContentEquals(foldVector, intArrayOf(mutable.key0, mutable.key1))
        assertContentEquals(foldVector, intArrayOf(immutable.key0, immutable.key1))
    }

    @Test
    fun next64_stream_matches_hash_sequence() {
        val mutable = ThreefryRandom(0L)
        var immutable = ThreefryRandom.Immutable(0L)

        for (expected in next64Vector) {
            assertEquals(expected, mutable.next64())
            val step = immutable.next64()
            assertEquals(expected, step.value)
            immutable = step.generator
        }
    }

    @Test
    fun next64_discards_partial_block_and_stays_counter_aligned() {
        val mutable = ThreefryRandom(0L)
        var immutable = ThreefryRandom.Immutable(0L)

        assertEquals(hashVectors[0].expected[0], mutable.next32())
        val first32 = immutable.next32()
        assertEquals(hashVectors[0].expected[0], first32.value)
        immutable = first32.generator

        assertEquals(next64Vector[1], mutable.next64())
        val step = immutable.next64()
        assertEquals(next64Vector[1], step.value)
    }

    @Test
    fun immutable_snapshot_round_trips_partial_buffer_state() {
        val seeded = ThreefryRandom(key0 = 0x12345678, key1 = 0x9abcdef0.toInt(), counter = 3L)
        seeded.next32()

        var original = seeded.asImmutable()
        var restored =
            ThreefryRandom.Immutable(
                key0 = original.key0,
                key1 = original.key1,
                counter = original.counter,
                block0 = original.block0,
                block1 = original.block1,
                blockIndex = original.blockIndex,
            )

        repeat(4) {
            val left64 = original.next64()
            val right64 = restored.next64()
            assertEquals(left64.value, right64.value)
            original = left64.generator
            restored = right64.generator

            val left32 = original.next32()
            val right32 = restored.next32()
            assertEquals(left32.value, right32.value)
            original = left32.generator
            restored = right32.generator
        }
    }

    @Test
    fun mutable_and_immutable_stay_in_lockstep() {
        val mutable = ThreefryRandom(key0 = 0x12345678, key1 = 0x9abcdef0.toInt(), counter = 3L)
        var immutable = ThreefryRandom.Immutable(key0 = 0x12345678, key1 = 0x9abcdef0.toInt(), counter = 3L)

        repeat(32) {
            val step = immutable.next32()
            assertEquals(mutable.next32(), step.value)
            immutable = step.generator
        }
    }

    @Test
    fun seed_constructor_matches_jax_key_layout() {
        val zero = ThreefryRandom(0L)
        val one = ThreefryRandom(1L)

        assertEquals(0, zero.key0)
        assertEquals(0, zero.key1)
        assertEquals(0, one.key0)
        assertEquals(1, one.key1)
    }

    @Test
    fun invalid_restore_block_index_is_rejected() {
        assertFailsWith<IllegalArgumentException> {
            ThreefryRandom(key0 = 0, key1 = 0, counter = 0L, block0 = 0, block1 = 0, blockIndex = 99)
        }
        assertFailsWith<IllegalArgumentException> {
            ThreefryRandom.Immutable(key0 = 0, key1 = 0, counter = 0L, block0 = 0, block1 = 0, blockIndex = -1)
        }
    }

    private data class HashVector(
        val key: IntArray,
        val count: IntArray,
        val expected: IntArray,
    )

    private companion object {
        // Generated by tools/export_random123_vectors.py using JAX 0.9.1.
        val hashVectors =
            listOf(
                HashVector(
                    key = intArrayOf(0, 0),
                    count = intArrayOf(0, 0),
                    expected = intArrayOf(1797259609, -1715843330),
                ),
                HashVector(
                    key = intArrayOf(1, 2),
                    count = intArrayOf(3, 4),
                    expected = intArrayOf(1576285164, -2045306482),
                ),
                HashVector(
                    key = intArrayOf(-1, 0),
                    count = intArrayOf(0, 1),
                    expected = intArrayOf(948974143, -108491105),
                ),
                HashVector(
                    key = intArrayOf(305419896, -1698898192),
                    count = intArrayOf(286331153, 572662306),
                    expected = intArrayOf(1731726502, 1441105921),
                ),
            )

        val splitVector =
            arrayOf(
                intArrayOf(1797259609, -1715843330),
                intArrayOf(928981903, -841280227),
                intArrayOf(-148943191, -1576124287),
                intArrayOf(-1827506293, -454500418),
            )

        val foldVector = intArrayOf(-1578141107, 292468403)

        val next64Vector =
            longArrayOf(
                7719171245655871230L,
                3989946895414531357L,
                -639706131588038527L,
                -7849079757828726850L,
            )
    }
}
