package one.wabbit.random

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith

class Xoshiro256RandomSpec {
    @Test
    fun xoshiro256_plus_plus_matches_exported_vectors() {
        val mutable = Xoshiro256PlusPlusRandom(1L, 2L, 3L, 4L)
        var immutable = Xoshiro256PlusPlusRandom.Immutable(1L, 2L, 3L, 4L)

        for (expected in plusPlusVector) {
            assertEquals(expected, mutable.next64())
            val step = immutable.next64()
            assertEquals(expected, step.value)
            immutable = step.generator
        }
    }

    @Test
    fun xoshiro256_star_star_matches_exported_vectors() {
        val mutable = Xoshiro256StarStarRandom(1L, 2L, 3L, 4L)
        var immutable = Xoshiro256StarStarRandom.Immutable(1L, 2L, 3L, 4L)

        for (expected in starStarVector) {
            assertEquals(expected, mutable.next64())
            val step = immutable.next64()
            assertEquals(expected, step.value)
            immutable = step.generator
        }
    }

    @Test
    fun jump_matches_exported_state_and_output_vectors() {
        val plusPlusMutable = Xoshiro256PlusPlusRandom(1L, 2L, 3L, 4L)
        val starStarMutable = Xoshiro256StarStarRandom(1L, 2L, 3L, 4L)

        plusPlusMutable.jump()
        starStarMutable.jump()

        assertEquals(jumpState.toList(), listOf(plusPlusMutable.s0, plusPlusMutable.s1, plusPlusMutable.s2, plusPlusMutable.s3))
        assertEquals(jumpState.toList(), listOf(starStarMutable.s0, starStarMutable.s1, starStarMutable.s2, starStarMutable.s3))

        var plusPlusImmutable = Xoshiro256PlusPlusRandom.Immutable(1L, 2L, 3L, 4L).jump()
        var starStarImmutable = Xoshiro256StarStarRandom.Immutable(1L, 2L, 3L, 4L).jump()

        assertEquals(jumpState.toList(), listOf(plusPlusImmutable.s0, plusPlusImmutable.s1, plusPlusImmutable.s2, plusPlusImmutable.s3))
        assertEquals(jumpState.toList(), listOf(starStarImmutable.s0, starStarImmutable.s1, starStarImmutable.s2, starStarImmutable.s3))

        for (expected in plusPlusJumpVector) {
            val step = plusPlusImmutable.next64()
            assertEquals(expected, step.value)
            plusPlusImmutable = step.generator
        }

        for (expected in starStarJumpVector) {
            val step = starStarImmutable.next64()
            assertEquals(expected, step.value)
            starStarImmutable = step.generator
        }
    }

    @Test
    fun long_jump_matches_exported_state_and_output_vectors() {
        val plusPlusMutable = Xoshiro256PlusPlusRandom(1L, 2L, 3L, 4L)
        val starStarMutable = Xoshiro256StarStarRandom(1L, 2L, 3L, 4L)

        plusPlusMutable.longJump()
        starStarMutable.longJump()

        assertEquals(longJumpState.toList(), listOf(plusPlusMutable.s0, plusPlusMutable.s1, plusPlusMutable.s2, plusPlusMutable.s3))
        assertEquals(longJumpState.toList(), listOf(starStarMutable.s0, starStarMutable.s1, starStarMutable.s2, starStarMutable.s3))

        var plusPlusImmutable = Xoshiro256PlusPlusRandom.Immutable(1L, 2L, 3L, 4L).longJump()
        var starStarImmutable = Xoshiro256StarStarRandom.Immutable(1L, 2L, 3L, 4L).longJump()

        assertEquals(longJumpState.toList(), listOf(plusPlusImmutable.s0, plusPlusImmutable.s1, plusPlusImmutable.s2, plusPlusImmutable.s3))
        assertEquals(longJumpState.toList(), listOf(starStarImmutable.s0, starStarImmutable.s1, starStarImmutable.s2, starStarImmutable.s3))

        for (expected in plusPlusLongJumpVector) {
            val step = plusPlusImmutable.next64()
            assertEquals(expected, step.value)
            plusPlusImmutable = step.generator
        }

        for (expected in starStarLongJumpVector) {
            val step = starStarImmutable.next64()
            assertEquals(expected, step.value)
            starStarImmutable = step.generator
        }
    }

    @Test
    fun seed_constructor_matches_splitmix64_export() {
        val plusPlus = Xoshiro256PlusPlusRandom(1L)
        val starStar = Xoshiro256StarStarRandom(1L)

        assertEquals(seedState.toList(), listOf(plusPlus.s0, plusPlus.s1, plusPlus.s2, plusPlus.s3))
        assertEquals(seedState.toList(), listOf(starStar.s0, starStar.s1, starStar.s2, starStar.s3))
    }

    @Test
    fun all_zero_state_is_rejected() {
        assertFailsWith<IllegalArgumentException> {
            Xoshiro256PlusPlusRandom(0L, 0L, 0L, 0L)
        }
        assertFailsWith<IllegalArgumentException> {
            Xoshiro256StarStarRandom(0L, 0L, 0L, 0L)
        }
    }

    private companion object {
        // Generated by tools/export_random123_vectors.py using the published xoshiro256 reference algorithm.
        val plusPlusVector =
            longArrayOf(
                41943041L,
                58720359L,
                3588806011781223L,
                3591011842654386L,
                -9218127359498767411L,
                -8473074601504656454L,
                -4435742961462588739L,
                -6040557928525160809L,
            )

        val starStarVector =
            longArrayOf(
                11520L,
                0L,
                1509978240L,
                1215971899390074240L,
                1216172134540287360L,
                607988272756665600L,
                -2273821095074991991L,
                8476171486693032832L,
            )

        val jumpState =
            longArrayOf(
                -8324317625228856367L,
                8079205330032121950L,
                7289065458748526725L,
                -8969279818415701936L,
            )

        val plusPlusJumpVector =
            longArrayOf(
                -1402993933574867913L,
                2364973248208838314L,
                -4495312427174064297L,
                8066193832155293345L,
            )

        val starStarJumpVector =
            longArrayOf(
                -4912596984176294952L,
                7126240192422241655L,
                3805973808039778091L,
                -6898863543051131232L,
            )

        val longJumpState =
            longArrayOf(
                678511610814637056L,
                -2596244294217022186L,
                6002989639035333134L,
                3559352929785830385L,
            )

        val plusPlusLongJumpVector =
            longArrayOf(
                -5348892935277310987L,
                5869259491745178931L,
                2145365994275058833L,
                -1751805903562324383L,
            )

        val starStarLongJumpVector =
            longArrayOf(
                5942309088398569549L,
                -2821296343772193180L,
                6925613901769781251L,
                -2247973468053884670L,
            )

        val seedState =
            longArrayOf(
                -7995527694508729151L,
                -4689498862643123097L,
                -534904783426661026L,
                8196980753821780235L,
            )
    }
}
